export enum NotificationType {
  PAYMENT_COMPLETE = 1,
  BOOKING_CONFIRMED = 2,
  BOOKING_CANCELLED = 3,
  BOOKING_REMINDER = 4,
  WALLET_DEPOSIT = 5,
  WALLET_WITHDRAW = 6,
  CHAT_MESSAGE = 7,
  TECHNICIAN_WALLET_NOT_ENOUGH = 8,
  STAFF_APPLY_SUCCESS = 9,
  STAFF_APPLY_REJECTED = 10,
  BOOKING_REFUNDED = 11,
  BOOKING_COMPLETED = 12,
  BOOKING_SUCCESS = 13,
  NEW_BOOKING_REQUEST = 14,
  BOOKING_AUTO_FINISHED = 15,
  BOOKING_OVERTIME_WARNING = 16,
  BOOKING_START = 17,
  WALLET_TRANSACTION_CANCELLED = 18,
}

export enum NotificationStatus {
  PENDING = 0, // Chờ gửi
  SENT = 1, // Đã gửi
  FAILED = 2, // Gửi thất bại
  READ = 3, // Đã đọc
}
