export enum _StorageKey {
  // SecureStorage
  SECURE_AUTH_TOKEN = 'SECURE_AUTH_TOKEN',
  SECURE_DEVICE_ID = 'SECURE_DEVICE_ID',

  // Storage
  LANGUAGE = 'LANGUAGE',
  USER_LOGIN = 'USER_LOGIN',
  BOOKING_TIME_KEY = 'BOOKING_TIME_KEY',
  NOTIFICATION_BOOKING = 'NOTIFICATION_BOOKING',
}
